#!/bin/sh
#                 _
#  _ __ ___   ___| |
# | '_ ` _ \ / __| |
# | | | | | | (__| |
# |_| |_| |_|\___|_|
#
# mcl - minecraft launcher
# see LICENSE for copyright details
# write `man mcl` for more details

MCLDIR="${MCLDOTDIR:-$HOME/.config/mcl}"
MCLPROFILES="$MCLDIR/profiles"
MCLPASSWD="$MCLDIR/passwd"
SELECTED="$(cat "$MCLPROFILES" | sed "s/\t.*$//g" | dmenu -l 30 -p "Please select a profile:")" || exit 1
ARGS="$(grep "$SELECTED" "$MCLPROFILES" | cut -f2 -d"	")"
cd $MCLDIR
[ -e ${MCLNOKILLFILE:-/tmp/mclnokill} ] || killall java
sh -c "minecraft-launcher-cmd --username $(sed -n 1p "$MCLPASSWD") --password $(sed -n 2p "$MCLPASSWD") $ARGS"
